#!/bin/sh
./scripts/dbreset.js
TOKEN_SECRET=test node server.js &
sleep 3
PID=$!
./node_modules/dredd/bin/dredd lib/apis/occ/occApi.apibp http://localhost:3000/api
RESULT=$?
kill -9 $PID
exit $RESULT
