#!/bin/sh
npm install -g dredd@0.3.0
./scripts/dbreset.js
TOKEN_SECRET=test node server.js &
sleep 3
PID=$!
dredd lib/apis/occ/occApi.apibp http://localhost:3000/api
RESULT=$?
kill -9 $PID
exit $RESULT
